version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_DATABASE: MYSQL_DB
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: 35.184.103.82
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: SPal51940*
      MYSQL_DB: mydb
